"""update base

Revision ID: 1143e2e8037a
Revises: f72e79529db3
Create Date: 2020-10-06 21:06:07.319529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1143e2e8037a'
down_revision = 'f72e79529db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('github_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'github_link')
    # ### end Alembic commands ###
